# Wed, 29 Jun 2016 10:27:48 +0200
timestamp = 1467188868

[netvars]
m_ArmorValue = 43496
m_Collision = 792
m_CollisionGroup = 1136
m_Local = 12200
m_MoveType = 600
m_OriginalOwnerXuidHigh = 12644
m_OriginalOwnerXuidLow = 12640
m_aimPunchAngle = 12312
m_aimPunchAngleVel = 12324
m_bGunGameImmunity = 14496
m_bHasDefuser = 43512
m_bHasHelmet = 43488
m_bInReload = 12853
m_bIsDefusing = 14484
m_bIsScoped = 14476
m_bSpotted = 2361
m_bSpottedByMask = 2428
m_dwBoneMatrix = 9880
m_fAccuracyPenalty = 12976
m_fFlags = 256
m_flFallbackWear = 12656
m_flFlashDuration = 41720
m_flFlashMaxAlpha = 41716
m_flNextPrimaryAttack = 12744
m_hActiveWeapon = 12008
m_hMyWeapons = 11752
m_hOwner = 10684
m_hOwnerEntity = 328
m_iAccountID = 12200
m_iClip1 = 12788
m_iCompetitiveRanking = 6724
m_iCompetitiveWins = 6984
m_iCrosshairId = 43588
m_iEntityQuality = 12172
m_iGlowIndex = 41744
m_iHealth = 252
m_iItemDefinitionIndex = 12168
m_iItemIDHigh = 12192
m_iShotsFired = 41648
m_iState = 12776
m_iTeamNum = 240
m_lifeState = 603
m_nFallbackPaintKit = 12648
m_nFallbackSeed = 12652
m_nFallbackStatTrak = 12660
m_nForceBone = 9852
m_nTickBase = 13332
m_rgflCoordinateFrame = 1088
m_szCustomName = 12316
m_szLastPlaceName = 13720
m_vecOrigin = 308
m_vecVelocity = 272
m_vecViewOffset = 260
m_viewPunchAngle = 12300

[signatures]
dwClientState = 5989124
dwClientState_GetLocalPlayer = 376
dwClientState_Map = 644
dwClientState_MapDirectory = 384
dwClientState_MaxPlayer = 776
dwClientState_State = 256
dwClientState_ViewAngles = 19724
dwEntityList = 77908740
dwForceAttack = 48810760
dwForceJump = 82714352
dwGameDir = 6637080
dwGlobalVars = 10638188
dwGlowObjectManager = 83241468
dwInput = 82408944
dwLocalPlayer = 10687748
dwMouseEnable = 10710376
dwPlayerResource = 48802608
dwRadarBase = 82319452
dwSensitivity = 10710284
dwViewMatrix = 77850276
dwWeaponTable = 82394204
dwWeaponTableIndex = 12896
dwbSendPackets = 916279
m_pStudioHdr = 10556
